config/routes.rb
Morethancoffee::Application.routes.draw do

  resources :users
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  resources :attendances, only: [:create, :destroy]

  post "users/email"
  root  "users#new"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :attendances
 	has_many :users, through: :attendances
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :attendances
  has_many :events, through: :attendances

	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    								uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def attending?(event)
    attendances.find_by(event_id: event.id)
  end

  def attending!(event)
    attendances.create!(event_id: event.id)
  end

  def notattending!(event)
    attendances.find_by(event_id: event.id).destroy
  end

  # def attending
  #   @title = "Attending"
  #   @user = User.find(params[:id])
  #   @events = @user.events
  #   render 'show_follow'
  # end

  # def followers
  #   @title = "Followers"
  #   @user = User.find(params[:id])
  #   @users = @user.followers.paginate(page: params[:page])
  #   render 'show_follow'
  # end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def create
    @event = Event.find(params[:attendance][:event_id])
    current_user.attending!(@event)
    redirect_to @event
  end

  def destroy
    @event = Attendance.find(params[:id]).event
    current_user.notattending!(@event)
    redirect_to @event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end

  def index 
  	@events = Event.all
  end

  def show
  	@event = Event.find(params[:id])
  	@users = @event.users
  	@sender =  current_user
  end

  def email

  	redirect_to 'index'
  end

  def update
    puts params.to_s
    @receiver = User.find(params[:user][:receiver_id])
    puts "This is the receiver " + @receiver.id.to_s
    @event = Event.find(params[:id])
    UserMailer.contact_email(current_user, @receiver, @event).deliver
    flash[:success] = "Email successfully sent!"
    redirect_to event_url
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
    else
        render 'edit'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :age, :lookingfor, :genderpref,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "More than Coffee"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def gravatar_for(user)
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/events/_attendance_form.html.erb
  <div id="attendance_form">
  <% if current_user.attending?(@event) %>
    <%= render 'signout' %>
  <% else %>
    <%= render 'signup' %>
  <% end %>
  </div>

app/views/events/_signout.html.erb
<%= form_for(current_user.attendances.find_by(event_id: @event.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Not attending", class: "custom-button btn btn-large" %>
<% end %>

app/views/events/_signup.html.erb
<%= form_for(current_user.attendances.build(event_id: @event.id)) do |f| %>
  <div><%= f.hidden_field :event_id %></div>
  <%= f.submit "Attending", class: "custom-button-big btn btn-large btn-primary" %>
<% end %>

app/views/events/index.html.erb
<% provide(:title, 'Events') %>
<h1>Events</h1>


<div class = "container">
	<% count = 1 %>
	<% while @events.count >= count %>
		<div class = "row">
			<% (0..2).each do |index| %>
				<%event = Event.find(count)%>
				<div class = "span4">
					<div class = "event" >
						<div class = "event-pic"> <img src = <%=event.picture%> ></div>
						<div class = "description">
							<%= link_to event.name, event %>
							<br>
							Start Time: <%=event.start_time.strftime("%m-%d-%Y, %I:%M%p")%><br>
							End Time: <%=event.end_time.strftime("%m-%d-%Y, %I:%M%p")%>
						</div>
						
				    </div>
			    </div>
			    <%count += 1%>
			<%end%>
		</div>	
	<%end%>			
</div>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/events/show.html.erb
<div class="span8">
  
      <ol class="users">
      	<%= @event.name %>
      	(<%= @users.count %> are going)
       	<%= render @users %>
      </ol>

      <div class = "span8">
      	<%=render 'attendance_form' %>
      </div>

 	 
 
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.yelp.com/search?cflt=coffee&find_loc=New+Haven%2C+CT">MoreThanCoffee</a>
    by Jenny and Natalia
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "More than Coffee", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Sign up", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%=debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>An online dating app around love of common activities! Meet someone while you go to an event you both love.</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p id="help">morethancoffeewebapp@gmail.com</p>

app/views/users/_user.html.erb
<li>
  <span class="gravatar"> 
     <%= gravatar_for user %>
  </span>
  <span class="name"><%= link_to user.name, user_path(user.id) %></span>
  

  <div class = "email-button">
  	<%= form_for user, url: {action: "update"} do |f| %>
  		<%= f.hidden_field :receiver_id, :value => user.id %>
  		<%= f.submit "Email this person!", class: "custom-button btn btn-small btn-primary" %>
  	<% end %> 
  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :age %>
      <%= f.number_field :age %>

      <%= f.label :lookingfor, "I'm looking for" %>
      <%= f.select :lookingfor, ["A fling", "A hook-up", "Soulmate", "Friendship", "Partner in Crime", "Wingman", "Galpal", "Frenemy", "Old-fashioned date", "Someone my parents will like"] %>

      <%=f.label :genderpref, "I'm romantically interested in" %>
      <%= f.select :genderpref, ["Female", "Male", "Both", "Something else", " It varies"] %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "custom-button-big button-custom btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1> All Users </h1>

<ul class="users"> 

<% @users.each do |user| %>
	<li>
		<%= gravatar_for user %>
		<%= link_to user.name, user %>
	</li> 
<%end%>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<fieldset class="main-border">
<div class="row">
  <div class="span5 offset2 submit-info">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "custom-button-big button-custom btn btn-large btn-primary"  %>
    <% end %>
  </div>
</div>
</fieldset>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %> 
      </h1>
      Age: <%= @user.age %> <br>
      Looking for: <%= @user.lookingfor %> <br>
      Romantic preference: <%= @user.genderpref %><br>
      Events that <%=@user.name %> is attending: 
      				<ul>
      				<% @user.events.each do |event| %>
    				<li> <%= link_to event.name, event_path(event.id) %> </li>
    				<% end %>
    				</ul>
    <%if @user == current_user%>
    	<%= link_to "Edit Profile", edit_user_path(current_user) %>
        &nbsp | &nbsp
    <% end %>
    	
    <%= link_to " Events", events_path %>
  </aside>
    </section>
    
   
</div>